export interface UserInfo {
        "avatar_url": string,
        "id": string,
        "login": string,
        "repos_url": string,
        "html_url": string,
        "bio": string,
        "blog": string,
        "company": string,
        "email": string,
        "followers": number,
        "following": number,
        "hireable": boolean,
        "location": string,
        "twitter_username"?:string,
        "name": string,
        "created_at": string,
}